# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/oem/Desktop/VXONE_V01_4K_120/VXONE_V01.srcs/sources_1/bd/CPU_block/ip/CPU_block_ilmb_v10_1/CPU_block_ilmb_v10_1.xci
# IP: The module: 'CPU_block_ilmb_v10_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/oem/Desktop/VXONE_V01_4K_120/VXONE_V01.gen/sources_1/bd/CPU_block/ip/CPU_block_ilmb_v10_1/CPU_block_ilmb_v10_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_block_ilmb_v10_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/oem/Desktop/VXONE_V01_4K_120/VXONE_V01.srcs/sources_1/bd/CPU_block/ip/CPU_block_ilmb_v10_1/CPU_block_ilmb_v10_1.xci
# IP: The module: 'CPU_block_ilmb_v10_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/oem/Desktop/VXONE_V01_4K_120/VXONE_V01.gen/sources_1/bd/CPU_block/ip/CPU_block_ilmb_v10_1/CPU_block_ilmb_v10_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_block_ilmb_v10_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
