# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/oem/Desktop/VXONE_V01_4K_120/VXONE_V01.srcs/sources_1/ip/vx1_phy/vx1_phy.xci
# IP: The module: 'vx1_phy' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/oem/Desktop/VXONE_V01_4K_120/VXONE_V01.srcs/sources_1/ip/vx1_phy/synth/vx1_phy_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vx1_phy'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/oem/Desktop/VXONE_V01_4K_120/VXONE_V01.srcs/sources_1/ip/vx1_phy/synth/vx1_phy.xdc
# XDC: The top module name and the constraint reference have the same name: 'vx1_phy'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/oem/Desktop/VXONE_V01_4K_120/VXONE_V01.srcs/sources_1/ip/vx1_phy/vx1_phy.xci
# IP: The module: 'vx1_phy' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/oem/Desktop/VXONE_V01_4K_120/VXONE_V01.srcs/sources_1/ip/vx1_phy/synth/vx1_phy_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vx1_phy'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/oem/Desktop/VXONE_V01_4K_120/VXONE_V01.srcs/sources_1/ip/vx1_phy/synth/vx1_phy.xdc
# XDC: The top module name and the constraint reference have the same name: 'vx1_phy'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
