# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/pin.xdc

# XDC: imports/xdc/us_vbone_phy_top.xdc

# XDC: imports/xdc/config.xdc

# XDC: imports/xdc/timing.xdc

# XDC: new/debug.xdc

# Block Designs: bd/CPU_block/CPU_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_block || ORIG_REF_NAME==CPU_block} -quiet] -quiet

# IP: bd/CPU_block/ip/CPU_block_dlmb_v10_1/CPU_block_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_block_dlmb_v10_1 || ORIG_REF_NAME==CPU_block_dlmb_v10_1} -quiet] -quiet

# IP: bd/CPU_block/ip/CPU_block_ilmb_v10_1/CPU_block_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_block_ilmb_v10_1 || ORIG_REF_NAME==CPU_block_ilmb_v10_1} -quiet] -quiet

# IP: bd/CPU_block/ip/CPU_block_dlmb_bram_if_cntlr_1/CPU_block_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_block_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==CPU_block_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/CPU_block/ip/CPU_block_ilmb_bram_if_cntlr_1/CPU_block_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_block_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==CPU_block_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/CPU_block/ip/CPU_block_lmb_bram_1/CPU_block_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_block_lmb_bram_1 || ORIG_REF_NAME==CPU_block_lmb_bram_1} -quiet] -quiet

# IP: bd/CPU_block/ip/CPU_block_mdm_1_1/CPU_block_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_block_mdm_1_1 || ORIG_REF_NAME==CPU_block_mdm_1_1} -quiet] -quiet

# IP: bd/CPU_block/ip/CPU_block_clk_wiz_1_1/CPU_block_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_block_clk_wiz_1_1 || ORIG_REF_NAME==CPU_block_clk_wiz_1_1} -quiet] -quiet

# IP: bd/CPU_block/ip/CPU_block_rst_clk_wiz_1_100M_0/CPU_block_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_block_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==CPU_block_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/CPU_block/ip/CPU_block_xbar_0/CPU_block_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_block_xbar_0 || ORIG_REF_NAME==CPU_block_xbar_0} -quiet] -quiet

# IP: bd/CPU_block/ip/CPU_block_axi_interconnect_0_0/CPU_block_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_block_axi_interconnect_0_0 || ORIG_REF_NAME==CPU_block_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/CPU_block/ip/CPU_block_axi_intc_0_0/CPU_block_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_block_axi_intc_0_0 || ORIG_REF_NAME==CPU_block_axi_intc_0_0} -quiet] -quiet

# IP: bd/CPU_block/ip/CPU_block_axi_amm_bridge_0_0/CPU_block_axi_amm_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_block_axi_amm_bridge_0_0 || ORIG_REF_NAME==CPU_block_axi_amm_bridge_0_0} -quiet] -quiet

# IP: bd/CPU_block/ip/CPU_block_xlconcat_0_0/CPU_block_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_block_xlconcat_0_0 || ORIG_REF_NAME==CPU_block_xlconcat_0_0} -quiet] -quiet

# IP: bd/CPU_block/ip/CPU_block_clk_wiz_0_0/CPU_block_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_block_clk_wiz_0_0 || ORIG_REF_NAME==CPU_block_clk_wiz_0_0} -quiet] -quiet

# IP: bd/CPU_block/ip/CPU_block_microblaze_0_2/CPU_block_microblaze_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_block_microblaze_0_2 || ORIG_REF_NAME==CPU_block_microblaze_0_2} -quiet] -quiet

# IP: bd/CPU_block/ip/CPU_block_axi_uartlite_0_0/CPU_block_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CPU_block_axi_uartlite_0_0 || ORIG_REF_NAME==CPU_block_axi_uartlite_0_0} -quiet] -quiet

# XDC: c:/Users/oem/Desktop/VXONE_V01_4K_120/VXONE_V01.gen/sources_1/bd/CPU_block/CPU_block_ooc.xdc
